kotlin.code.style=official

groupId=ru.kotlix
versionIdNumber=1.0.2
versionIdStatus=SNAPSHOT

# our dependencies
frameRouterVersion=1.0.5-SNAPSHOT
frameAuthVersion=1.2.1-SNAPSHOT
framePartiesVersion=1.0.1-SNAPSHOT
frameStateVersion=1.0.2-SNAPSHOT

# plugins
js2pojoVersion=1.2.2
protobufProtocVersion=4.28.2
protobufVersion=0.9.5
jvmPluginVersion=2.0.21
springBootVersion=3.3.5
springCloudVersion=2023.0.3
springDependencyManagementVersion=1.1.6
ktlintVersion=12.1.1
