apiVersion: v1
kind: ConfigMap
metadata:
  name: ${KTX_APP_NAME}
data:
  application.yaml: |
    netty:
      server:
        port: 8080

    spring:
      kafka:
        bootstrap-servers: ${KAFKA_ADDRESS}
        consumer:
          group-id: session
          auto-offset-reset: latest
          session-timeout-ms: 5000
          heartbeat-interval-ms: 2000
          max-poll-interval-ms: 10000
      cloud:
        openfeign:
          client:
            config:
              frame-auth-client:
                url: http://frame-auth:8080
              frame-state-client:
                url: http://frame-state:8080
              frame-parties-community-client:
                url: http://frame-parties:8080

    session:
      kafka:
        authentication:
          username: ${KAFKA_USER}
          password: ${KAFKA_PASSWORD}
        consumer:
          topic: ${KAFKA_TOPIC}
      login-timeout: 30000
      heartbeat-timeout: 300000

    logging:
      level:
        ru.: DEBUG
